timeout: 3600s
tags:
  - canary-deploy-demo
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _CLUSTER_NAME: ${CLUSTER_NAME}

options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-install-image"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=build-image/cloudbuild.yaml --substitutions=_PROJECT_ID=${_PROJECT_ID}

- name: "gcr.io/${_PROJECT_ID}/canary-deploy-demo-installer"
  id: "canary-deploy-demo"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}
      #canary deploy
      export HELLO_APP_V1_VERSION=$(kubectl get destinationrules hello-app-dr -ojson | jq -r .spec.subsets[0].labels.version)
      export TAG_NAME=$(date +%y%m%d-%H%M%S)
      export HELLO_APP_V2_VERSION=${TAG_NAME}
      export HELLO_APP_V2_IMAGE=gcr.io/${PROJECT_ID}/hello-app:${HELLO_APP_V2_VERSION}

      #modify main.go
      cat main.go.tpl| envsubst > golang-template/main.go

      gcloud builds submit --substitutions=_PROJECT_ID=${PROJECT_ID},TAG_NAME=${TAG_NAME}

      cat destination-rule.yaml.tpl| envsubst > demo/destination-rule.yaml
      cat hello-app-deployment-v2.yaml.tpl| envsubst > demo/hello-app-deployment-v2.yaml

      kubectl apply -f demo/hello-app-deployment-v2.yaml
      kubectl apply -f demo/destination-rule.yaml
      kubectl apply -f demo/vs-90-10.yaml
      kubectl apply -f demo/vs-50-50.yaml
      kubectl apply -f demo/vs-10-90.yaml

      # very important
      cat destination-rule-single-svc.yaml.tpl| envsubst > demo/destination-rule.yaml
      kubectl apply -f demo/destination-rule.yaml
      kubectl apply -f demo/vs-100-0.yaml

      kubectl delete deploy hello-app-deployment-${HELLO_APP_V1_VERSION}
  waitFor:
    - build-install-image

# - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#   id: "cloud-deploy"
#   entrypoint: bash
#   args:
#     - '-c'
#     - >
#       gcloud beta deploy releases create simple-gameserver-rel-$TAG_NAME
#       --delivery-pipeline=clouddeploy-demo
#       --region=us-central1 --annotations=commitId=v1
#       --images=my-app-image=gcr.io/${PROJECT_ID}/simple-game-server:$TAG_NAME
