timeout: 3600s
tags:
  - canary-deploy-demo
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_ZONE: ${GCP_ZONE}
  _CLUSTER_NAME: ${CLUSTER_NAME}

options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-base-image"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=build-image/cloudbuild.yaml --substitutions=_PROJECT_ID=${_PROJECT_ID}

- name: "gcr.io/${_PROJECT_ID}/canary-deploy-demo-base"
  id: "canary-deploy-demo"
  entrypoint: 'bash'
  dir: "istio-template"
  args:
    - '-xe'
    - '-c'
    - |
      export CLUSTER_NAME=${_CLUSTER_NAME}
      export GCP_ZONE=${_GCP_ZONE}
      export PROJECT_ID=${_PROJECT_ID}
      ./run-canary-deploy.sh
  waitFor:
    - build-base-image

# - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#   id: "cloud-deploy"
#   entrypoint: bash
#   args:
#     - '-c'
#     - |
#       gcloud beta deploy releases create simple-gameserver-rel-$TAG_NAME
#       --delivery-pipeline=clouddeploy-demo
#       --region=us-central1 --annotations=commitId=v1
#       --images=my-app-image=gcr.io/${PROJECT_ID}/simple-game-server:$TAG_NAME
