tags:
  - hello-app
substitutions:
  _PROJECT_ID: ${PROJECT_ID}

steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "update-project-id"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i'' -e "s/PROJECT_ID/${_PROJECT_ID}/g" skaffold.yaml

- name: gcr.io/k8s-skaffold/skaffold
  id: "skaffold-build"
  args:
    - skaffold
    - build
    - '--interactive=false'
    - '--file-output=artifacts.json'
    - '--tag=$TAG_NAME'

# - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#   id: "cloud-deploy"
#   entrypoint: bash
#   args:
#     - '-c'
#     - >
#       gcloud beta deploy releases create simple-gameserver-rel-$TAG_NAME
#       --delivery-pipeline=clouddeploy-demo
#       --region=us-central1 --annotations=commitId=v1
#       --images=my-app-image=gcr.io/${PROJECT_ID}/simple-game-server:$TAG_NAME
