apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: hello-app
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/PROJECT_ID/hello-app
    docker:
      dockerfile: ./Dockerfile
# deploy:
#   kubectl:
#     manifests:
#       - ./examples/simple-game-server/fleet_configs_simple.yaml
