tags:
  - canary-deploy-demo
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-base-image'
  args:
  - --destination=gcr.io/${_PROJECT_ID}/canary-deploy-demo-base
  - --cache=true
  - --cache-ttl=12h
